version: "4.1"
services:
  server:
    build:
      context: .
    container_name: "${API_CONTAINER_NAME}"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tariff
    ports:
      - "${API_PORT}:8080"
    depends_on:
      - db
      - selenium
    restart: always
  db:
    image: "postgres:${DB_POSTGRES_VERSION}"
    container_name: "${NAME_DB_CONTAINER}"
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      PGDATA: "/var/lib/postgresql/data/pgdata"

    ports:
      - "${DB_PORT}:5432"
    restart: unless-stopped

  selenium:
    image: "selenium/standalone-firefox:latest"
    ports:
      - "4444:4444"